include: package:lint/analysis_options.yaml

analyzer:

  errors:

    prefer_const_constructors: error


linter:
  rules:

    always_put_required_named_parameters_first: true

    avoid_classes_with_only_static_members: false

    sort_constructors_first: true

    prefer_single_quotes: true

    public_member_api_docs: false

    always_specify_types: true

    lines_longer_than_80_chars: false