---
name: warframe
description: Just building my favorite game mobile app
publish_to: none
version: 0.0.3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  animations: ^2.0.2

  connectivity_plus: ^2.1.0

  cupertino_icons: ^1.0.4

  dartz: ^0.10.1

  equatable: ^2.0.3

  flutter:
    sdk: flutter

  http: ^0.13.3

  json_annotation: ^4.0.1

  provider: ^6.0.1

  url_launcher: ^6.0.8

  webview_flutter: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.1

  lint: ^1.5.3

  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - images/
