---
name: warframe
description: Just building my favourite game mobile app
publish_to: none
version: 0.0.3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  
  animations:

  connectivity: ^3.0.6

  cupertino_icons: ^1.0.3

  dartz: 0.10.0-nullsafety.2

  equatable: ^2.0.3

  flutter:
    sdk: flutter
  
  http: ^0.13.3
  
  json_annotation: ^4.0.1

  provider: ^5.0.0

  url_launcher: ^6.0.8

dev_dependencies:
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.3

  lint: ^1.5.3

  mocktail: ^0.1.4

flutter:
  uses-material-design: true
  assets:
    - images/
