---
name: warframe
description: Just building my favourite game mobile app
publish_to: none
version: 0.0.3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  
  animations:

  cupertino_icons: ^1.0.3

  flutter:
    sdk: flutter

  json_annotation: ^4.0.1

  provider: ^5.0.0

  url_launcher: ^6.0.8

  http: ^0.13.3

dev_dependencies:
  lint: any
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
